apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pdns-recursor.fullname" . }}
  labels:
    {{- include "pdns-recursor.labels" . | nindent 4 }}
data:
  recursor.conf: |
    disable-syslog=yes
    local-address=127.0.0.1:5300
    socket-dir=/tmp

  dnsdist.conf: |
    addDOHLocal("127.0.0.1:8053")
    newServer("127.0.0.1:5300")
