apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "unbound.fullname" . }}
spec:
  secretName: {{ include "unbound.fullname" . }}-tls
  dnsNames:
    - {{ .Values.ingress.host }}
  issuerRef:
    name: {{ .Values.certificate.issuer.name }}
    kind: {{ .Values.certificate.issuer.kind }}
