apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "unbound.fullname" . }}
  labels:
    {{- include "unbound.labels" . | nindent 4 }}
data:
  unbound.conf: |
    server:
      chroot: ""
      username: ""
      directory: "/unbound/etc/unbound"
      use-syslog: no
      pidfile: "/unbound/etc/unbound/unbound.pid"
      interface: 0.0.0.0@4430
      interface: ::0@4430
      https-port: 4430
      tls-service-key: "/unbound/etc/unbound/tls/tls.key"
      tls-service-pem: "/unbound/etc/unbound/tls/tls.crt"
