{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "unbound.fullname" . }}
  labels:
    {{- include "unbound.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    {{- if .values.ingress.issuer.cluster }}
    cert-manager.io/cluster-issuer: {{ .Values.ingress.issuer.name }}
    {{- else }}
    cert-manager.io/issuer: {{ .Values.ingress.issuer.name }}
    {{- end }}
spec:
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ include "unbound.fullname" . }}-tls
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "unbound.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
{{- end }}
